"use client";

import { useState } from "react";
import { ProfileLayout } from "./ProfileLayout";
import { RequestInfo } from "rwsdk/worker";
import { colors } from "@/app/theme";
import { Notification } from "@/db/schema/user-schema";

// Mock notifications generated by Claude based on Notification schema
const mockNotifications: Notification[] = [
  {
    id: 1,
    userId: 1,
    notificationType: "message",
    title: "New message",
    message: "You have received a new message.",
    read: 0,
    createdAt: "2025-11-02T10:00:00Z",
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 2,
    userId: 1,
    notificationType: "review",
    title: "New review",
    message: "Someone left you a review.",
    read: 1,
    createdAt: "2025-11-01T09:00:00Z",
    updatedAt: null,
    deletedAt: null,
  },
  {
    id: 3,
    userId: 1,
    notificationType: "request",
    title: "Swap request",
    message: "You received a new swap request.",
    read: 0,
    createdAt: "2025-10-31T15:00:00Z",
    updatedAt: null,
    deletedAt: null,
  },
];

export interface NotificationsPageProps {
  ctx: RequestInfo;
  notifications?: Notification[];
}

export function NotificationsPage({
  ctx,
  notifications,
}: NotificationsPageProps) {
  const [notificationList, setNotificationList] = useState<Notification[]>(
    notifications || mockNotifications
  );

  const handleNotificationClick = (notification: Notification) => {
    setNotificationList((prev) =>
      prev.map((n) => (n.id === notification.id ? { ...n, read: 1 } : n))
    );

    // TODO: Mark as read in backend

    // Navigate to messages for message notifications
    // TODO: Add navigation for other notification types
    if (notification.notificationType === "message") {
      window.location.href = "/profile/messages";
    }
  };

  return (
    <ProfileLayout ctx={ctx}>
      <main className="p-4">
        {/* Notifications box */}
        <section
          className="max-w-4xl mx-auto rounded-lg shadow p-6 min-h-[500px]"
          style={{ background: colors.neutral.white }}
        >
          <h2
            className="text-2xl font-semibold mb-4"
            style={{ color: colors.neutral.black }}
          >
            Notifications
          </h2>
          <div>
            {notificationList.length === 0 ? (
              <div
                className="text-center py-8"
                style={{ color: colors.neutral.gray[500] }}
              >
                Ingen notifikasjoner å vise
              </div>
            ) : (
              notificationList.map((notification) => (
                <div
                  key={notification.id}
                  role="button"
                  tabIndex={0}
                  aria-label={`${notification.title}`}
                  className="border rounded mb-3 p-4 flex justify-between items-center"
                  style={{
                    borderColor: colors.neutral.gray[400],
                    background:
                      notification.read === 0
                        ? colors.neutral.gray[100]
                        : colors.neutral.white,
                    cursor: "pointer",
                  }}
                  onClick={() => handleNotificationClick(notification)}
                >
                  <div>
                    <div
                      className="font-medium flex items-center gap-2"
                      style={{ color: colors.neutral.black }}
                    >
                      {/* SVG icons */}
                      {notification.notificationType === "review" && (
                        <svg
                          width="20"
                          height="20"
                          viewBox="0 0 20 20"
                          fill="none"
                          aria-hidden="true"
                        >
                          <path
                            d="M10 15.27L16.18 18l-1.64-7.03L20 7.24l-7.19-.61L10 0 7.19 6.63 0 7.24l5.46 3.73L3.82 18z"
                            fill={colors.primary.main}
                          />
                        </svg>
                      )}
                      {notification.notificationType === "request" && (
                        <svg
                          width="20"
                          height="20"
                          viewBox="0 0 20 20"
                          fill="none"
                          aria-hidden="true"
                        >
                          <path
                            d="M2 4a2 2 0 012-2h12a2 2 0 012 2v12a2 2 0 01-2 2H4a2 2 0 01-2-2V4zm2 0v12h12V4H4zm2 3h8v2H6V7zm0 4h5v2H6v-2z"
                            fill={colors.primary.main}
                          />
                        </svg>
                      )}
                      {notification.notificationType === "message" &&
                        (notification.read === 0 ? (
                          <svg
                            width="20"
                            height="20"
                            viewBox="0 0 24 24"
                            fill="none"
                            aria-hidden="true"
                          >
                            <path
                              fill={colors.primary.main}
                              d="M2 6.5V18a2 2 0 002 2h16a2 2 0 002-2V6.5l-10 7.5-10-7.5Z"
                            />
                            <path
                              fill={colors.primary.main}
                              d="M22 6a2 2 0 00-2-2H4a2 2 0 00-2 2v.5l10 7.5 10-7.5V6Z"
                            />
                          </svg>
                        ) : (
                          <svg
                            width="20"
                            height="20"
                            viewBox="0 0 24 24"
                            fill="none"
                            aria-hidden="true"
                          >
                            <path
                              fill={colors.primary.main}
                              d="M2 8.5V18a2 2 0 002 2h16a2 2 0 002-2V8.5l-10 7.5-10-7.5Z"
                            />
                            <path
                              fill={colors.primary.main}
                              d="M22 8a2 2 0 00-2-2H4a2 2 0 00-2 2v.5l10 7.5 10-7.5V8Z"
                            />
                            <path
                              fill={colors.primary.main}
                              d="M2 6V4a2 2 0 012-2h16a2 2 0 012 2v2"
                            />
                          </svg>
                        ))}
                      <span>{notification.title}</span>
                    </div>
                    <div
                      className="text-sm"
                      style={{ color: colors.neutral.gray[600] }}
                    >
                      {notification.message}
                    </div>
                    <div
                      className="text-xs mt-1"
                      style={{ color: colors.neutral.gray[500] }}
                    >
                      {new Date(notification.createdAt).toLocaleString()}
                    </div>
                  </div>
                </div>
              ))
            )}
          </div>
        </section>
      </main>
    </ProfileLayout>
  );
}
